---
abstract: 'a 2d point object in cartesian space with utility angle methods'
author:
  - 'David Farrell <sillymoos@cpan.org>'
build_requires:
  Test::Exception: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-Shape-Point
requires:
  Carp: '0'
  Math::Trig: '0'
  Regexp::Common: '0'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/sillymoose/Math-Shape-Point
  repository: https://github.com/sillymoose/Math-Shape-Point.git
version: '0.09'
